### ISSUE TITLE
virmet tidytable does not finish if one sample doesn't contain any viral reads

### ISSUE THREAD

**Issue by sschmutz** [medvir/VirMet#39]
Happens sometime (negative controls) that there are sequences, but no viral ones. If `virmet tidytable` is then used, following error is returned and it stops there
`FileNotFoundError: File b'NTC-DNA_S3/stats.tsv' does not exist`

This example is from the analysis `virmet_output_180720_M01274_0227_000000000-BY9JM`
@ozagordi

**Comment by mihuber** [comment]
See also here
`virmet tidytable --outdir ../virmet_output_191004_M01274_0291_000000000-CNNV4/`
> FileNotFoundError: [Errno 2] File b'NTC-RNA_S7/orgs_list.tsv' does not exist: b'NTC-RNA_S7/orgs_list.tsv'
