### ISSUE TITLE
read_table is deprecated, use read_csv instead

### ISSUE THREAD

**Issue by sschmutz** [medvir/VirMet#47]
FutureWarning: read_table is deprecated, use read_csv instead.

We should probably replace this in `tidytable.py` to avoid future issues.

https://github.com/medvir/VirMet/blob/97351c2ce47f5538530fcb5b4cfc8caf1f16d3e6/src/virmet/tidytable.py#L27
https://github.com/medvir/VirMet/blob/97351c2ce47f5538530fcb5b4cfc8caf1f16d3e6/src/virmet/tidytable.py#L34

**Comment by MaryamZaheri** [comment]
Solved this issue in pull request "tidytable works with Samples without viral reads #48".
