### ISSUE TITLE
virmet covplot not working because of missing ggplot package

### ISSUE THREAD

**Issue by mihuber** [medvir/VirMet#49]
Virmet covplot did run and generated a depth.txt file, but no plot because of missing ggplot package?
Error message: `Error in library(ggplot2) : there is no package called ‘ggplot2’`
Conda base environment was used.
Example here: `/analyses/VirMetResults/virmet_output_191010_M01274_0292_000000000-CNPVH/1000458456-BE-DNA_S3/Torque/`

**Comment by MaryamZaheri** [comment]
Solved on Timavo
