### ISSUE TITLE
virmet wolfpack --run doesn't work if run_name starts with a 2

### ISSUE THREAD

**Issue by sschmutz** [medvir/VirMet#50]
I'm not sure if this is the only line of code which causes this issue:

https://github.com/medvir/VirMet/blob/d6fd569ac4325c3ed6a2cc6720a3f0ccaee82dc3/src/virmet/wolfpack.py#L504

To reproduce issue try running `virmet wolfpack --run /data/MiSeq/MiSeqOutput/200110_M01274_0316_000000000-CW5HM/` on `timavo`

**Comment by MaryamZaheri** [comment]
The issue is temporarily solved on timavo. I will modify this repository soon.
